### PR TITLE
Item objects

### PR DESCRIPTION
**Pull request by rayalois22**
Hello, 
I added a SQL file and an image file for items.
What's missing?

### CODE REVIEW

**Comment by Acrunam** [comment]
Hi Alois, 

You need to merge this latest commit you made to the main branch so that we can see the changes. Meanwhile, I'm making a new pull request. I've added a customer class with some boiler plate code and a customers_sql just to start things off on my end and build from there.

**Review by RaymondMwaura — APPROVED** [review]
Seems OK. I think you can call the database something like "shopping-assistant-db" so that you can logically merge it with our sql code.

**Review by RaymondMwaura — APPROVED** [review]
I think it's a good starting point. We can begin with this and modify later if needed.

**Comment by rayalois22** [comment]
Okay.  Thanks.
I am now merging it into master.

**Pull request merged**
